### PR TITLE
Fixed the actual gap

### PR DESCRIPTION
**Pull request by tharmaman**
gap

Screen Shot 2021-07-29 at 3 19 34 PM

### CODE REVIEW

**Review by sarthak-marwaha — APPROVED** [review]
Why was status taking 12 columns? Unless something is taking up 2 rows which shouldn't even be possible

**Comment by tharmaman** [comment]
> Why was status taking 12 columns? Unless something is taking up 2 rows which shouldn't even be possible

Think status was 6 but came before assignedTo in terms of order which didn't have any cols defined, so I think it defaulted to 12 and so it appeared as if status took 12 cols

**Comment by sarthak-marwaha** [comment]
> > Why was status taking 12 columns? Unless something is taking up 2 rows which shouldn't even be possible
> 
> Think status was 6 but came before assignedTo in terms of order which didn't have any cols defined, so I think it defaulted to 12 and so it appeared as if status took 12 cols

Then it should have been next to Group anyway since it had the space?

**Comment by tharmaman** [comment]
> > > Why was status taking 12 columns? Unless something is taking up 2 rows which shouldn't even be possible
> > 
> > 
> > Think status was 6 but came before assignedTo in terms of order which didn't have any cols defined, so I think it defaulted to 12 and so it appeared as if status took 12 cols
> 
> Then it should have been next to Group anyway since it had the space?

Not if 

> > > Why was status taking 12 columns? Unless something is taking up 2 rows which shouldn't even be possible
> > 
> > 
> > Think status was 6 but came before assignedTo in terms of order which didn't have any cols defined, so I think it defaulted to 12 and so it appeared as if status took 12 cols
> 
> Then it should have been next to Group anyway since it had the space?

Resolved on Slack, basically pritee's example had an extra prop from TransactionApprovalRequest will post how it looks like with that property

**Pull request merged**
