### PR TITLE
searching on createdFor

### PR DESCRIPTION
**Pull request by Nauna**
NEW - with search filter - createdFor

image

OLD

image

### CODE REVIEW

**Review by jlhughes — APPROVED** [review]

**Review by tharmaman — APPROVED** [review]

**Review by tharmaman — CHANGES_REQUESTED** [review]
So wait createdFor is a reference this will just show the id no, and search will only work if you search the id?

**Review by tharmaman — APPROVED** [review]

**Comment by tharmaman** [comment]
> So wait createdFor is a reference this will just show the id no, and search will only work if you search the id?
resolved in slack

**Comment by jlhughes** [comment]
re: just search on id - correct. 
@Nauna this search works for you?

**Comment by tharmaman** [comment]
> re: just search on id - correct.
> @Nauna this search works for you?

She said it uses the RichChoiceView in search. Then we have a tableCellFormatter on CreatedFor.

**Comment by Nauna** [comment]
So its been difficult to test - since I cleared my jrls and have had blockers in dev.

I've tested searching by name only.

**Review by jlhughes — APPROVED** [review]

**Pull request merged**
