### PR TITLE
prevent duplicated ucjs

### PR DESCRIPTION
**Pull request by smirnovaka**

### CODE REVIEW

**Review by jlhughes — COMMENTED** [review]
If there is a match, set the incoming id to the old, so a create becomes an update.
Perhaps a better name, such as UserCapabilityJunctionMergeDuplicateDAO or similar. 
Also, should log that it's occurring (just info) just in case it was unexpected.

**Comment by kgrgreer** [comment]
Isn't this only a problem because we added the 'id' property to UCJ's? Can't we just remove it? What would it break?

**Comment by smirnovaka** [comment]
> Isn't this only a problem because we added the 'id' property to UCJ's? Can't we just remove it? What would it break?

* userCapabilityJunctionTransactionJunctionDAO relies on tx id and ucj's id
* businessDirectorDAO stores ucj's id
* AccountingProvider stores ucj's id
* DowJonesApprovalRequest stores ucj's id
* used in UCJReportHandler

**Comment by smirnovaka** [comment]
@Nauna are the files above going to be affected by the change? The id is updated in the local internal dao, at the end of the chain, so up until that moment the ucj basically has an invalid id.

**Comment by Nauna** [comment]
Consider ucj's tied to business and users.
So something like the signing officer would be associated to both the realUser and business, since a user can be assigned to multiple businesses.
This type of capability is defined by capability.associatedEntity = AssociatedEntity.ACTING_USER

In the crunchService the code to find is - updated a bit for readability -...
```
var ucj = isAssociation
      ? new AgentCapabilityJunction.Builder(x)
        .setSourceId(subject.getRealUser().getId())
        .setTargetId(capabilityId)
        .setEffectiveUser(subject.getUser().getId())
        .build()
      : new UserCapabilityJunction.Builder(x)
        .setSourceId(associatedUser.getId())
        .setTargetId(associatedEntity == AssociatedEntity.USER
                 ? subject.getUser()
                 : subject.getRealUser())
        .build();
   ``` 
 SOOO, if the find in UserCapabilityJunctionSanityDAO.js can return the wrong ucj.

**Comment by kgrgreer** [comment]
If we remove the 'id' property then the system will add a fake id property which combines the user and capability ID's.

**Pull request closed without merging**
