### PR TITLE
[Np 4998] prevent duplicate labels entry

### PR DESCRIPTION
**Pull request by Mykola97**
https://nanopay.atlassian.net/browse/NP-4998

### CODE REVIEW

**Comment by adamfox-nanopay** [comment]
This is just a new guys observation ... but wouldnt it be better to modify ReferenceArrayView to filter out previously selected items, as this would then solve this problem for all usages of ReferenceArrayView. (if that is even possible)
The problem I see here is that a user may accidentally select a label that they had already selected thinking they have now 2 labels assigned, but when we save it will silently remove one of those labels.

**Comment by lchanmann** [comment]
ReferenceArrayView is just one view, to really prevent it from having duplicate entry would be the server side job.

**Comment by lchanmann** [comment]
@Mykola97 can you resolve the conflict?

**Comment by Mykola97** [comment]
> @Mykola97 can you resolve the conflict?

Updated

**Review by lchanmann — APPROVED** [review]

**Pull request merged**
