### PR TITLE
Only allow primitive types for theme replacement

### PR DESCRIPTION
**Pull request by sarthak-marwaha**
Block any empty objects from being used in theme replacement (cause default values to be ignored).
Screen Shot 2021-11-29 at 2 28 58 PM

### CODE REVIEW

**Comment by kgrgreer** [comment]
When/how are empty objects being used?

**Comment by sarthak-marwaha** [comment]
> When/how are empty objects being used?

In cases where the root is defined but a child is not. Like inputHeight is a child of theme but since theme is defined the path function actually goes into the for loop. I initially added the strict parameter to avoid this but we didn't want to use that approach

**Comment by kgrgreer** [comment]
I think this is caused by a bug in foam.util.path in lib.js, if we change that to:

  util:     {
    path: function(root, path, opt_ensure) {
      var a = path.split('.');

      for ( var i = 0 ; i < a.length ; i++ ) {
        root = root[a[i]];
        if ( root === undefined ) {
          if ( opt_ensure ) {
            root = root[a[i]] = {};
          } else {
            return;
          }
        }
      }

      return root;
    }
  },

Then we don't need this check.

**Comment by kgrgreer** [comment]
Actually, here's a tested version of that method:
  util:     {
    path: function(root, path, opt_ensure) {
      var a = path.split('.');

      for ( var i = 0 ; i < a.length ; i++ ) {
        var nextRoot = root[a[i]];
        if ( nextRoot === undefined ) {
          if ( opt_ensure ) {
            nextRoot = root[a[i]] = {};
          } else {
            return;
          }
        }
        root = nextRoot;
      }

      return root;
    }
  },

**Comment by kgrgreer** [comment]
commit 5019c73cbf981a52c23d01734389a66cd6a70b64
Author: Kevin Greer <kgrgreer@gmail.com>
Date:   Mon Dec 13 13:01:49 2021 -0500

    Fix foam.lib.path() method to not create children when opt_ensure isn't enabled.

**Comment by sarthak-marwaha** [comment]
Fixed with linked commit

**Pull request closed without merging**
