### PR TITLE
Save ucj data on granted bug fix

### PR DESCRIPTION
**Pull request by jinnnn9**
1. In `SaveUcjDataOnGranted`, use oldObj from the method parameter instead of getting the old obj from dao find. If the rule is an after rule, the dao find returns the new object not the old object, and this causes the save not to happen.

2. Update the predicate - remove a space after/before the opening/closing bracket to fix parsing error

### CODE REVIEW

**Review by jlhughes — APPROVED** [review]

**Comment by noodlemoodle** [comment]
lgtm，this doesnt break anything？

**Comment by jinnnn9** [comment]
> lgtm，this doesnt break anything？

Nothing I noticed. Anything you are concerned of?

**Comment by jlhughes** [comment]
> lgtm，this doesnt break anything？

@jinn9 This flow is tested during the PaymentRequestSubscriptionFeeTest.  Have you run tests cases?

**Comment by jinnnn9** [comment]
> > lgtm，this doesnt break anything？
> 
> @jinn9 This flow is tested during the PaymentRequestSubscriptionFeeTest. Have you run tests cases?

Yeah all the tests passed for me except the bank holiday bank service test. This test was failing even before I made the update.

**Pull request merged**
