### PR TITLE
[NP-5042] - Rename user group auth permission string

### PR DESCRIPTION
**Pull request by nanopay-arthur**
Ref: https://nanopay.atlassian.net/browse/NP-5042

### CODE REVIEW

**Review by zahnno — COMMENTED** [review]
I suggest user.read.byGroup since the permission implies on user.read.* will still permit this check - having the action and property in the same segment removes the inherit wildcard value of permission implies.

_*Pardon the repost._

**Comment by jlhughes** [comment]
@nanopay-arthur please comment on @zahnno proposal. Thanks

**Comment by nanopay-arthur** [comment]
@zahnno Good point - the idea behind it was that we could keep the structure of having the permission string be made up of three parts instead of 4 parts (ie. user.read.byGroup.treviso-sme). @kgrgreer had his concerns about the 4 part approach, but I agree that we want to keep in mind the user.read.* permission.

**Comment by kgrgreer** [comment]
If someone has user.read.* then they have access to all of the data anyway, and don't need the user.readByGroup permission. The problem with user.read.byGroup would be that someone could create a user with id 'byGroup.*' and then gain access to read all users. And while this isn't possible as long as User.id is a Long, it could happen for other DAOs/Models and I would rather have a convention that we can use consistently everywhere.

**Pull request merged**
