### PR TITLE
Added type css to non-nanos apps | Fixed Enum demo

### PR DESCRIPTION
**Pull request by sarthak-marwaha**

### CODE REVIEW

**Comment by kgrgreer** [comment]
In Window.js, we do:
      this.installCSS(`
        .foam-u2-Element-hidden {
          display: none !important;
        }
      `, 'global', 'Window');

To install global / required CSS. Could we add type.js there, or put it in a Model that automatically gets included? Otherwise, people need to know that they also need to install this CSS in order to work properly. Same as with some of the other odd bits of CSS.

**Comment by sarthak-marwaha** [comment]
These styles are already in AppStyles model so if we implement that in Window.js then that should solve our problem

**Comment by kgrgreer** [comment]
Let's discuss next week.

**Comment by kgrgreer** [comment]
DO NOT MERGE.
I would prefer a solution which doesn't require having to load a css file in order to get a useable appearance.

**Comment by sarthak-marwaha** [comment]
Already fixed with https://github.com/kgrgreer/foam3/pull/297

**Pull request closed without merging**
