### PR TITLE
Add fruler pred

### PR DESCRIPTION
**Pull request by smirnovaka**

### CODE REVIEW

**Comment by jlhughes** [comment]
I'm confused. FScriptPredicate already works as a the predicate for rules.

**Comment by smirnovaka** [comment]
@jlhughes yes, it already works as a predicate for rules, but it does so because we add explicit support for it in the Rule model ( https://github.com/kgrgreer/foam3/blob/development/src/foam/nanos/ruler/Rule.js#L354 . Ideally we want Rule not to be aware of these details. Because of this hardcoded  logic we are not capable to combine regular predicates with fscript predicates via AND

**Review by KernelDeimos — APPROVED** [review]
Tested this and it works, allows me to use an FScript predicate in the [UCJ edit behaviour PR](https://github.com/kgrgreer/foam3/pull/2515)

**Comment by KernelDeimos** [comment]
> I'm confused. FScriptPredicate already works as a the predicate for rules.

see my last comment on https://github.com/kgrgreer/foam3/pull/2515 - fscript predicates in the ruler don't currently work if they're nested inside other predicates like `And`. Kristina's new PR is how it probably should have been done in the first place.

**Comment by jlhughes** [comment]
It's the other way around, we don't want mlang FScriptPredicate to be aware of the Ruler and RuleData, new, old.

**Pull request merged**
