### PR TITLE
[NP-9548] Move 'Resend Code' below the Verify button on the sign-up code verification screen

### PR DESCRIPTION
**Pull request by Mykola97**
https://nanopay.atlassian.net/browse/NP-9547

### CODE REVIEW

**Comment by noodlemoodle** [comment]
i dont think this would work

**Comment by noodlemoodle** [comment]
will ping you when i have a solution for this @Mykola97

**Comment by Mykola97** [comment]
> i dont think this would work

What do you mean?  @noodlemoodle 
Screenshot 2023-07-12 at 2 49 18 PM

**Comment by noodlemoodle** [comment]
ticket says resend code is supposed to go under submit. and even if you changed the order it wouldn't work since submit is an action of the wizardlet while resendcode is an action of the emailverificationcode model @Mykola97

**Comment by Mykola97** [comment]
> ticket says resend code is supposed to go under submit. and even if you changed the order it wouldn't work since submit is an action of the wizardlet while resendcode is an action of the emailverificationcode model @Mykola97

I was thinking image on ticket is a design. Thank you for explanation

**Comment by Mykola97** [comment]
https://github.com/nanoPayinc/NANOPAY/pull/16811

**Pull request closed without merging**
