### PR TITLE
reference.view now set to RichChoiceView

### PR DESCRIPTION
**Pull request by Nauna**
Tested on GroupPermissionJunction

Screen Shot 2023-01-09 at 9 16 15 AM
referenceUpgrade

### CODE REVIEW

**Comment by sarthak-marwaha** [comment]
Dont think this is a good idea across the board, in this case we should change the view on the property itself

**Review by jlhughes — APPROVED** [review]

**Comment by jlhughes** [comment]
@sarthak-marwaha I would prefer RichChoiceView be the default, and a model can revert to ChoiceView if desired.  Thoughts? 
@kgrgreer

**Comment by sarthak-marwaha** [comment]
> @sarthak-marwaha I would prefer RichChoiceView be the default, and a model can revert to ChoiceView if desired. Thoughts?
> @kgrgreer

@jlhughes Switching all reference views to richChoice is fine by me but this approach removes the ChoiceView completely, probably better to have the RichReferenceView be a subclass of the existing one

**Comment by jlhughes** [comment]
> > @sarthak-marwaha I would prefer RichChoiceView be the default, and a model can revert to ChoiceView if desired. Thoughts?
> > @kgrgreer
> 
> @jlhughes Switching all reference views to richChoice is fine by me but this approach removes the ChoiceView completely, probably better to have the RichReferenceView be a subclass of the existing one

I like this idea.  @Nauna can you do that?

**Comment by Nauna** [comment]
@sarthak-marwaha not sure I understand your meaning here:
>this approach removes the ChoiceView completely, probably better to have the RichReferenceView be a subclass of the existing one

This approach is setting the default view for references as RichChoiceView.
It's changing the default behaviour, if a property(reference) wants a choiceView, it is suppose to set the ChoiceView as its view.

The removal of ChoiceView is for the default - are you saying we have two views setup for defaults, such that we can change the default back and forth? If that is the case then I wouldn't recommend that. Mainly cause there is one default, if we are deciding this is the default then I see no reason to keep stale code.

*** update - 
I think I see what you mean, please confirm:
ReferencePropertyView - set that to RichChoiceView,
but since ReferenceView is used in multiple other locations, leave that as ChoiceView...correct? I can do this

**Comment by sarthak-marwaha** [comment]
> @sarthak-marwaha not sure I understand your meaning here:
> 
> > this approach removes the ChoiceView completely, probably better to have the RichReferenceView be a subclass of the existing one
> 
> This approach is setting the default view for references as RichChoiceView. It's changing the default behaviour, if a property(reference) wants a choiceView, it is suppose to set the ChoiceView as its view.
> 
> The removal of ChoiceView is for the default - are you saying we have two views setup for defaults, such that we can change the default back and forth? If that is the case then I wouldn't recommend that. Mainly cause there is one default, if we are deciding this is the default then I see no reason to keep stale code.
> 
> *** update - I think I see what you mean, please confirm: ReferencePropertyView - set that to RichChoiceView, but since ReferenceView is used in multiple other locations, leave that as ChoiceView...correct? I can do this

@Nauna Reference view extends ChoiceView so with the current code there would be no implementation of ReferenceView that can use ChoiceView since `extends` cannot be changed by changing the viewspec and also just setting the view to choiceView doesnt work either since referenceView does some work for us by picking the right DAO to assign choices and then providing the correct labels for them. So if we want a ReferenceView that uses RichChoiceView we should make a new one instead of updating this one.

As for your point about default views, yes but also cant set it directly to richChoiceView since richChoiceView expects daos and stuff to be preset in the viewspec so you would have to create a new one

**Review by sarthak-marwaha — APPROVED** [review]

**Pull request merged**
