### PR TITLE
updating window hash on signout

### PR DESCRIPTION
**Pull request by olhabn**
ticket https://nanopay.atlassian.net/browse/NP-4684

### CODE REVIEW

**Comment by kgrgreer** [comment]
We don't want to hardcode a reference to a nanopay specific menu "sme.accountProfile.signout" into a generic nanos class.
@Nauna Why is signout nanopay or worse, sme specific in the first place? If we could move to nanos then this would be fine.

**Comment by kgrgreer** [comment]
Another option would be to modify 
package: 'net.nanopay.ui',
name: 'Controller',
so that it vetoes memento changes to this value. That would be okay since that is nanopay specific code.

**Comment by kgrgreer** [comment]
Or just reset the memento before logging out.

**Comment by olhabn** [comment]
> Or just reset the memento before logging out.

will do. thanks!

**Comment by kgrgreer** [comment]
Fixed by:

commit c71c438dc51c2d4a51b4f01322e96e0d0049cc31 (HEAD -> development, origin/development, origin/HEAD)
Author: Kevin Glen Roy Greer <kgrgreer@gmail.com>
Date:   Fri Jun 11 13:49:09 2021 -0400

    Update AccountProfileView to reset hash on logout.
    
    Was causing loops on logout. Fixes NP-4684

**Pull request closed without merging**
