### PR TITLE
Removed empty export driver element from the view

### PR DESCRIPTION
**Pull request by sarthak-marwaha**
image

### CODE REVIEW

**Review by blakegreen32 — COMMENTED** [review]
@sarthak-marwaha You tested on data management and regular menus? Export worked fine on both?

**Comment by sarthak-marwaha** [comment]
> @sarthak-marwaha You tested on data management and regular menus? Export worked fine on both?

@blakegreen32 Yup. Tested on Users and User DAO. Both work

**Review by blakegreen32 — APPROVED** [review]
LGTM

**Review by olhabn — APPROVED** [review]

**Comment by olhabn** [comment]
LGTM

**Pull request merged**
